const express = require("express");
const router = express.Router();
const postsRouter = require("../admin/posts.route");
const userRouter = require("../admin/users.route");
const categoriesRouter = require("../admin/categories.route");
const productsRouter = require("../admin/products.route");
const commentsRouter = require("../admin/comments.route");
const analyticsRouter = require("../admin/analytics.route");
const settingsRouter = require("../admin/settings.route");
const accountsettingsRouter = require("../admin/accountsettings.route");
const loginRouter = require("../admin/login.route");
const registerRouter = require("../admin/register.route");
const forgotPasswordRouter = require("../admin/forgotPassword.route");
const resetPasswordRouter = require("../admin/resetPassword.route");

router.use("/users", userRouter);
router.use("/posts", postsRouter);
router.use("/categories", categoriesRouter);
router.use("/products", productsRouter);
router.use("/comments", commentsRouter);
router.use("/analytics", analyticsRouter);
router.use("/settings", settingsRouter);
router.use("/accountsettings", accountsettingsRouter);
router.use("/login", loginRouter);
router.use("/register", registerRouter);
router.use("/forgotPassword", forgotPasswordRouter);
router.use("/resetPassword", resetPasswordRouter);
module.exports = router;
